version: '3.8'
services:
  link-db:
    image: postgres:13
    container_name: link-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: adm
      POSTGRES_DB: link-db
    networks:
      - link-cutter

  client:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://adm:adm@link-db:5432/link-db
      - BASE_URL=http://localhost:3000
    networks:
      - link-cutter

networks:
  link-cutter:
