version: '3.8'
services:
  link-db:
    image: postgres:13
    container_name: link-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: adm
      POSTGRES_DB: link-db
